### ISSUE TITLE
pb compiling

### ISSUE THREAD

**Issue by guigeek208** [fabiand/gst-plugins-cl#2]
Hi,
i want to compile the plugin but i have many errors : 
openclbasetransform.vala:88.16-88.48: error: Assignment: Cannot convert from `GOpenCL.Device[]' to `Gst.Device[]?'
      Device[] devices = platform.get_devices ();
openclbasetransform.vala:94.7-94.38: error: Assignment: Cannot convert from `GOpenCL.Context' to `Gst.Context'
      ctx = platform.create_context ();
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I use GStreamer 1.6.2, maybe it's a compatibility problem ?
Thanks for your help,
Best regards,

**Comment by fabiand** [comment]
Hey - Thanks for the issue. And yes, it's a compat issue.

gst-plugins-cl were written with gstreamer 0.10 and were never ported to gstreamer 1.x.

**Comment by fabiand** [comment]
I'd be _happy_ to see PRs on adding gst 1.x support!

I think there is veen a branch where I started to work on this support.
